### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by iamsmug** [gimenete/iOS-boilerplate#12]
If you change the delegate on the ImageManager to tabbar (if it's a tabbar app), images don't appear in the tableView till that cell has either passed the top or botom of the screen. Images on a normal detail view don't show at all.

**Comment by gimenete** [comment]
This is because ImageManager notifies all viewcontrollers that the image was loaded. But it supposes that you are using navigationcontroller only. You need to change the code a little to make it working with a tabbarcontroller.

Nevertheless. I have replaced ASIHTTPRequest by AFNetworking and with this changes ImageManager no longer iterates over all viewcontrollers, so this problem has disappeared. This is a major change. Let me know if you have problems migrating the code or you want to keep using ASIHTTPRequest and don't know what to change to make it work.

http://iosboilerplate.com/

**Comment by iamsmug** [comment]
Thanks Aberto

I will give it a go and let you know how I got on.

Cheers

Anthony

**Comment by iamsmug** [comment]
Hi Alberto

I have been trying the new iOSBiolerplate using the AFNetworks implementation but have got into some trouble with my JSON that was working on the other release. My JSON is here:

http://www.zombiedesign.co.uk/zing/index.php?searchby=city&city=blackpool

The AFNetworks JSON request fails with this result:

got text/html

Any ideas, I have checked my JSON and it is valid?

Cheers

Anthony

**Comment by gimenete** [comment]
Hi,

Your .php script should return an http header ContentType = text/json

Nevertheless, if you cannot change the php script you can do this:

operation.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/html", nil];

before calling [operation start]

Hope this helps!
